### ISSUE TITLE
Feature request: set default section

### ISSUE THREAD

**Issue by tukkek** [MicroPad/MicroPad-Core#142]
It would be great to expand on #118 by also having the last used section open by default. Or at least consider that, if there is only one section in a notebook, it should open that one by default on launch.

I realize that many people must have several notebooks and sections but for someone like me who only needs one, it feels weird to not have uPad automatically open it for me upon launch.

Thanks for the great package and hard work put into it!

**Comment by NickGeek** [comment]
Would opening your last note automatically be even nicer?

**Comment by tukkek** [comment]
I am not sure what you mean by it, would you please clarify it for me?

**Comment by NickGeek** [comment]
Notes are what go in sections, so what MicroPad could do, is automatically open up the note that was last open when you launch the app.

**Comment by tukkek** [comment]
What is important to me is that the main board not be needlessly blank when I open up uPad from the AppImage. If it can remember which "board" I was using last, that would be great :) (I thought the "board" was called section, inside a notebook).

I am sorry but I'm still pretty new to the program so I might be misunderstanding the nomenclature.

Another option would be "set default" but since in the mentioned issue you decided to go with a "remember last" instead, I believe that would be just as good or even better.

**Comment by NickGeek** [comment]
Oh, all good, I get what you mean.

A note is what you're calling a "board", a section can contain notes and sub-sections. Notebooks contain sections.

If you've used OneNote:

| OneNote | MicroPad |
|-----------|-----------------|
| Notebook | Notebook/Notepad |
| Section Group | Section |
| Note | Note |

**Comment by NickGeek** [comment]
This has been done!
