### ISSUE TITLE
Drawing: Weird behavour when releasing mouse-press outside canvas

### ISSUE THREAD

**Issue by pagdot** [MicroPad/MicroPad-Core#190]
**Describe the bug**
Weird behaviour in drawing element, when leaving frame while mouse is pressed and releasing mouse in popup, but not in canvas. Lines get still drawn and if the mouse is pressed, dragged and release an additional line gets drawn between the start and release point of this movement.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create drawing element
2. Start drawing
3. Leave popup while drawing
4. Enter popup, but nor drawing canvas with mouse
5. Release mouse
6. Reenter drawing canvas

**Expected behaviour**
Line gets finished

**Screenshots**

![Peek 2019-09-24 20-46](https://user-images.githubusercontent.com/2229858/65540878-9130b200-df0c-11e9-8486-ef735efbbb05.gif)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser Chromium, Firefox, Electron App
 - µPad Version: v3.21.0

**Comment by NickGeek** [comment]
Thanks for the bug report. I've reproduced this.
