### ISSUE TITLE
Is it possible to get back word wrap in the editor?

### ISSUE THREAD

**Issue by corypanshin** [MicroPad/MicroPad-Core#193]
The release notes say word wrap was removed to make it easier to use notes for lists and code.  However, I need to be able to write in paragraphs in order to jot down ideas, describe problems I'm working on, etc. The lack of word wrap makes this impossible.  I would like to see an option to enable word wrap again.

**Comment by NickGeek** [comment]
Yep, that's totally doable! I'll probably have some sort of checkbox or something for that right by the editor.

**Comment by corypanshin** [comment]
The following section of this message contains a file attachment
prepared for transmission using the Internet MIME message format.
If you are using Pegasus Mail, or any other MIME-compliant system,
you should be able to save it or view it from within your mailer.
If you cannot, please ask your system administrator for assistance.

   ---- File information -----------
     File:  DEFAULT.BMP
     Date:  19 Nov 2001, 17:00
     Size:  358 bytes.
     Type:  Unknown

**Comment by NickGeek** [comment]
I can't see that image, you'll need to go to https://github.com/MicroPad/Web/issues/193 and add it.

**Comment by corypanshin** [comment]
I didn't send an image -- just absent-mindedly hit Reply to the email instead of coming back here.  But what I wrote was "Cool.  That would be great!  Thank you for your rapid response."

**Comment by NickGeek** [comment]
Oh, sweet. No problem :-)

**Comment by NickGeek** [comment]
Added in MicroPad v4 (see https://next.getmicropad.com for the experimental build)
