### ISSUE TITLE
Panning via middle mouse button.

### ISSUE THREAD

**Issue by Tinkergod** [MicroPad/MicroPad-Core#237]
I think this app would be more usable if you could pan via middle mouse button. It is kind of a drag to have to scroll via bars.
Want to help with implementing but I'm not sure where to get started. If you could point me to the right piece of code I need to be looking at that would be of great help.

**Comment by NickGeek** [comment]
Hi, agreed. On Windows it seems like the electron app doesn't get this behaviour but the functionally identical web app (https://web.getmicropad.com) does. I personally use a mouse with left/right scroll on it or laptops with trackpads that can scroll.

I'm not sure what the main approach here would be but https://github.com/MicroPad/MicroPad-Core/blob/master/app/src/app/components/note-viewer/NoteViewerComponent.tsx would be a good place to look.

#100 is the same feature request so I'm going to close this one and paste this message over there too.
