### ISSUE TITLE
Glitch when drag one box over the other

### ISSUE THREAD

**Issue by MGuerrera** [MicroPad/MicroPad-Core#361]
When you move one box on top of another it often freezes, jerks, and it becomes frustrating to move and organize. 
My Specs:
- Win10
- Intel Core i7 2.40GHz
- 16 GB RAM

![X2qXQu9hSu](https://user-images.githubusercontent.com/15629810/123267421-4850c780-d4fd-11eb-9c93-cf49d30838e9.gif)

**Comment by NickGeek** [comment]
I suspect it's because we lose mouse tracking when it clips with the iframe in those markdown boxes.

**Comment by NickGeek** [comment]
This has been fixed in MicroPad v4 (see dev-preview at https://next.getmicropad.com)

**Comment by MGuerrera** [comment]
Thank you, good work =)
