### ISSUE TITLE
Essential Tweaks

### ISSUE THREAD

**Issue by Ansh4011** [MicroPad/MicroPad-Core#371]
Hi, 
I really like **MicroPad**, I recently installed it. To be honest, it is a very beautiful peace of software, but a few basic improvements which me as a totally new user actually expected like any other normal user. They are as followed-
1. I think the context menu should open by right click, I know it may not matter much, but any normal user would expect a right click, keeping in mind that everyone are using the right click context menu from years, this will make it really more user friendly.
2. While moving/dragging a tile, I found a delay in the tile from the mouse. Like I moved the tile to the other side, but after some distance the tile was left behind while the mouse was away from it. In short the mouse is not in sync with the tile while shifting it here and there.

That's it for now as far as I have used! 
Thanks for this great peace of software :).

**Comment by Ansh4011** [comment]
Ps->  Today I was trying to delete one the files from microsync, but I am not able to delete it, I don't know why though.

**Comment by NickGeek** [comment]
Thanks for the feedback! When you say "context menu" are you referring to the "insert element" one?

Element dragging especially has issues with markdown elements right now because they embed an IFrame. I have a few ideas to try out to improve it but I haven't tried any yet.

To stop syncing a notebook you can use the option on the sidebar in MicroPad with the red underline.

**Comment by Ansh4011** [comment]
Yea! The Insert Element one.

Oh, the dragging is fine for time being.

I have been trying the same but no outcome. I clicked the _Stop syncing this notepad_ button several times but it always get's back to the same stage. 
![image](https://user-images.githubusercontent.com/84930340/126890551-6aa6280f-3af1-49d2-8711-1c61a2ceed25.png)
Also, while using the same notebook which is in sync, it again and again pops out the message saying 'Only undefined may edit this notebook, because they are the scribe.' 
![image](https://user-images.githubusercontent.com/84930340/126890572-9071008f-fee9-41c4-a5da-8bdf3bee4752.png)

**Comment by NickGeek** [comment]
Hmm that's an odd bug. @Ansh4011 could you please either post your MicroSync username here or email it to the address on https://getmicropad.com/contact.html?

**Comment by Ansh4011** [comment]
Ya sure, my username is 'Ansh'.
And thanks for the quick support :).

**Comment by Ansh4011** [comment]
> Hmm that's an odd bug. @Ansh4011 could you please either post your MicroSync username here or email it to the address on https://getmicropad.com/contact.html?

Ya sure, my username is 'Ansh'.
And thanks for the quick support :).

**Comment by NickGeek** [comment]
Hi @Ansh4011! Your notebook should be gone now. Still wasn't able to hunt down why that didn't work for you. I assume it was probably some caching inconsistencies. I'll add the context menu click for insert to the list of things to do for MicroPad v4 (you can see the current experimental one at https://next.getmicropad.com)

**Comment by Ansh4011** [comment]
> Hi @Ansh4011! Your notebook should be gone now. Still wasn't able to hunt down why that didn't work for you. I assume it was probably some caching inconsistencies. I'll add the context menu click for insert to the list of things to do for MicroPad v4 (you can see the current experimental one at https://next.getmicropad.com)

Oh, Thanks a lot buddy for helping me out! Have a great day ahead! And yea, keep it up! :)

**Comment by Ansh4011** [comment]
Hi, just giving another recommendation for the beta version! So the micropad controls area is in the left but that does not sync actually, like all the tabs (themes, notebooks, search, etc.) are in the right, and the controls panels in the left, so that makes it a bit less user friendly and decreases the productivity because otherwise in the current stable version all the things related to the notes is in the right side itself, so it makes it more convenient for using.
![image](https://user-images.githubusercontent.com/84930340/126927362-116aa084-c384-4af7-8b9f-33e07f8e9cab.png)
![image](https://user-images.githubusercontent.com/84930340/126927445-39a6a2f3-fa0f-414a-b4b5-b4757e5a17a8.png)
So, technically that can cause problems as far as I think.
