### ISSUE TITLE
Support for youtube videos (interesting imo)

### ISSUE THREAD

**Issue by Ansh4011** [MicroPad/MicroPad-Core#373]
Can we get support for playing youtube videos within micropad, link just paste the link of the video in a youtube video playing element and the video starts playing with the controllers, etc. Being a student myself, I would love this feature wherein I can make notes along with video lectures on youtube which save a lot of time, increases productivity, makes it more convenient to use and ofcourse it saves the Alt+tab frustration. This seemed a cool and worthy to share feature so just shared it. Thanks!

**Comment by NickGeek** [comment]
Did you manage to get this working or is it a feature you would no longer like?
