### ISSUE TITLE
local yarn typecheck produces more errors than CI-Pipeline

### ISSUE THREAD

**Issue by Jonas-July** [MicroPad/MicroPad-Core#387]
**Describe the bug**
When running `yarn typecheck` locally (using next-dev or new-colours) on my Linux system, I get the following errors that don't appear in the results produced by the CI-Pipeline in GitHub:
```
[me@mymachine ~/micropad-core/app] yarn typecheck
yarn run v1.22.17
$ tsc --noEmit --p ./tsconfig.json
src/app/components/search/SearchComponent.tsx:7:18 - error TS2614: Module '"react-select"' has no exported member 'GroupBase'. Did you mean to use 'import GroupBase from "react-select"' instead?

7 import Select, { GroupBase } from 'react-select';
                   ~~~~~~~~~

src/app/components/search/SearchComponent.tsx:60:6 - error TS2578: Unused '@ts-expect-error' directive.

60      // @ts-expect-error TS-2322, the type definitions from the library are wrong, they say we get a
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 2 errors.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```
They don't appear when the CI-Pipeline in GitHub runs on new-colours

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the micropad/app
2. Type "yarn typecheck"
3. The above errors will appear

**Expected behaviour**
These errors should not appear, or at least they should be picked up by the CI-Pipeline

**Desktop (please complete the following information):**
Linux machine using the latest micropad code

**Additional context**

**Comment by NickGeek** [comment]
You'll need to re-run `yarn` to get the latest dependencies
