### ISSUE TITLE
Crashed x2

### ISSUE THREAD

**Issue by PRCOY1** [MicroPad/MicroPad-Core#399]
I was trying this (3.30.3) out and had it crash twice on me.
Surface Pro-8, Win11 home.
I opened a drawing box. At the bottom, selected a date  3/4/2022 (tomorrow) then clicked the clock and it crashed when I clicked on the hour 12. I tried it again and it repeated.
I ended up with a window full of teal background color, the top windows border and nothing else. It did manage to save the drawing and other "notes". So +1

**Comment by NickGeek** [comment]
https://web.getmicropad.com is updating now. I’ll make an electron release shortly.

**Comment by NickGeek** [comment]
@PRCOY1 Just released v3.30.5 with a fix
