### ISSUE TITLE
Instant crash on kali linux

### ISSUE THREAD

**Issue by Pruizcoder** [MicroPad/MicroPad-Core#412]
Micropad crashes the second i try to open it.
installed from the snap store on kali linux

**Comment by NickGeek** [comment]
@Pruizcoder Hi, that's not good. I'll look into it. In the meantime does the AppImage or .deb version run for you?

Also, what version of Kali Linux are you running?

**Comment by NickGeek** [comment]
@Pruizcoder Could you also please try and open MicroPad from the terminal and post what it prints. To open micropad from the terminal, open your terminal and type in `micropad`.

**Comment by Pruizcoder** [comment]
tried to uninstall it and install the deb package but nothing changed, the kali version is 2022.3, just updated, if i try to run it form the terminal i get this message `[2470:1005/091337.173541:FATAL:gpu_data_manager_impl_private.cc(894)] The display compositor is frequently crashing. Goodbye.
zsh: trace trap  micropad
`

**Comment by NickGeek** [comment]
Hmm, I just installed Kali and it ran fine for me. According to some searching it appears that there is a bug with how Electron interacts with the proprietary NVIDIA driver (see https://www.reddit.com/r/openSUSE/comments/srbswv/any_suggestions_with_running_appimage/)

The suggested fix is to launch the app with `micropad --disable-gpu-sandbox` or `micropad --no-sandbox`.

Hopefully a future release of Electron or the NVIDIA driver will fix this issue. If neither of these work, you can access MicroPad with your browser by going to https://web.getmicropad.com. The browser version of MicroPad is fully featured with the same functionality and privacy as the desktop version.

**Comment by Pruizcoder** [comment]
your suggested fix worked, it's strange that it's a Nvidia graphics driver problem since i have a radeon ATI graphics card on my pc

**Comment by NickGeek** [comment]
Weird. I'll close this for now. Thanks for bringing this to my attention.
