### ISSUE TITLE
Automatic recognition PDF files.

### ISSUE THREAD

**Issue by Bai-Hu** [MicroPad/MicroPad-Core#433]
**Is your feature request related to a problem? Please describe.**
When dragging a PDF file into the micropad window, it will be inserted into the notebook as a regular file.

**Describe the solution you'd like**
When dragging a PDF file into the micropad window, it will be inserted into the notebook as a PDF file and display it, just like images.

**Describe alternatives you've considered**
Add options to files that have already been inserted.

**Additional context**
Micropad is amazing, it's the best notebook I've ever seen for a heavy markdown and latex user on Linux.

**Comment by NickGeek** [comment]
This is currently live on https://next.getmicropad.com and will be shipped with version 4.9.0.
